# Generated by Django 6.0.3 on 2026-03-31 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=150)),
                ('book_type', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('available', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='issueBookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, default=None, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('fine_amount', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned')], default='issued', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_book', to='management_app.bookdata')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.bookdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.userdata')),
            ],
        ),
    ]
