# Generated by Django 6.0.3 on 2026-03-31 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='user_name',
            new_name='full_name',
        ),
    ]
