# Generated by Django 6.0.3 on 2026-03-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_rename_user_name_userdata_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='book_type',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('History', 'History'), ('Biography', 'Biography'), ('Technology', 'Technology'), ('Literature', 'Literature'), ('Other', 'Other')], max_length=20),
        ),
    ]
